JPAWeb/src/java/entity/Employee.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import org.hibernate.validator.constraints.NotEmpty;
import javax.validation.*;

/**
 *
 * @author Berry
 */
@Entity
@Table(name = "employee")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Employee.findAll", query = "SELECT e FROM Employee e"),
    @NamedQuery(name = "Employee.findById", query = "SELECT e FROM Employee e WHERE e.id = :id"),
    @NamedQuery(name = "Employee.findByNama", query = "SELECT e FROM Employee e WHERE e.nama = :nama"),
    @NamedQuery(name = "Employee.findBySalary", query = "SELECT e FROM Employee e WHERE e.salary = :salary")})
public class Employee implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    //@Basic(optional = false)
    //@NotNull
    //@Column(name = "id")
    //@NotEmpty(message="ID Tidak Boleh Kosong")
    private Integer id;
    @Size(max = 50)
    @Column(name = "nama")
    @NotEmpty(message="Nama Tidak Boleh Kosong")
    private String nama;
    @Column(name = "salary")
    //@NotEmpty(message="Salary Tidak Boleh Kosong")
    //@Min(value=1000, message="Salary Minimal 1000")
    private Integer salary;

    public Employee() {
    }

    public Employee(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNama() {
        return nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public Integer getSalary() {
        return salary;
    }

    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Employee)) {
            return false;
        }
        Employee other = (Employee) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entity.Employee[ id=" + id + " ]";
    }
    
}

JPAWeb/src/java/controller/EmployeeController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import entity.Employee;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import javax.ejb.EJB;
import service.EmployeeFacade;
import java.util.List;

/**
 *
 * @author Berry
 */
@Named(value = "employeeController")
@SessionScoped
public class EmployeeController implements Serializable {

    /**
     * Creates a new instance of EmployeeController
     */
    public EmployeeController() {
    }
    
    @EJB
    EmployeeFacade empf;
    
    private Employee employee;
    
    public List<Employee> getAllEmployee() {
        return empf.findAll();                
    }
    
    public Employee getEmployee() {
        return employee;
    }
    
    public String prepareCreate() {
        employee = new Employee();
        return "/AddEmployee";
    }
    
    public String createEmployee() {
        empf.create(employee);
        return "/index";
    }
    
    public String prepareEdit(int id) {
        employee = empf.find(id);
        return "/EditEmployee";
    }
    
    public String editEmployee() {
        empf.edit(employee);
        return "/index";
    }
    
    public String deleteEmployee(int id) {
        employee = empf.find(id);
        empf.remove(employee);
        return "/index";
    }
            
}

JPAWeb/web/AddEmployee.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Add Employee</title>
    </h:head>
    <h:body>
        <f:view>           
            <h:form>
                <f:validateBean>
                    <h1><h:outputText value="Create/Edit"/></h1>
                    <h:panelGrid columns="2">
                        <h:outputLabel value="Id:" for="id" />
                        <h:inputText id="id" value="#{employeeController.employee.id}" title="Id" required="true" requiredMessage="The Id field is required."/>                        
                        <h:outputLabel value="Nama:" for="nama" />
                        <h:inputText id="nama" value="#{employeeController.employee.nama}" title="Nama" />                                                                   
                        <h:outputLabel value="Salary:" for="salary" />
                        <h:inputText id="salary" value="#{employeeController.employee.salary}" title="Salary" />
                        <h:commandButton value="Save" action="#{employeeController.createEmployee()}"/>                        
                    </h:panelGrid>
                </f:validateBean>
                
            </h:form>
        </f:view>

    </h:body>
</html>

JPAWeb/web/EditEmployee.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <f:view>


            <h:form>
                <h1><h:outputText value="Create/Edit"/></h1>
                <f:validateBean>
                    <h:panelGrid columns="2">
                        <h:outputLabel value="Id:" for="id" />
                        <h:inputText id="id" value="#{employeeController.employee.id}" title="Id" required="true" requiredMessage="The Id field is required."/>
                        <h:outputLabel value="Nama:" for="nama" />
                        <h:inputText id="nama" value="#{employeeController.employee.nama}" title="Nama" />
                        <h:outputLabel value="Salary:" for="salary" />
                        <h:inputText id="salary" value="#{employeeController.employee.salary}" title="Salary" />
                        <h:commandButton value="Save" action="#{employeeController.editEmployee()}"/>
                    </h:panelGrid>
                </f:validateBean>                
            </h:form>
        </f:view>
    </h:body>
</html>

JPAWeb/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Data Employee</title>
    </h:head>
    <h:body>
        <f:view>
            <h:form>
                <h1><h:outputText value="List Employee"/></h1>
                <h:dataTable value="#{employeeController.allEmployee}" var="item">
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Id"/>
                        </f:facet>
                        <h:outputText value="#{item.id}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Nama"/>
                        </f:facet>
                        <h:outputText value="#{item.nama}"/>                        
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Salary"/>
                        </f:facet>
                        <h:outputText value="#{item.salary}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Edit"/>
                        </f:facet>
                        <h:commandButton value="Edit" action="#{employeeController.prepareEdit(item.id)}"/>
                        <h:commandButton value="Delete" action="#{employeeController.deleteEmployee(item.id)}"/>                        
                    </h:column>
                </h:dataTable>
                <h:commandButton value="Add Employee" action="#{employeeController.prepareCreate()}"/>
            </h:form>
        </f:view>
    </h:body>
</html>