RumahSakit/src/java/entity/Doctor.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Berry
 */
@Entity
@Table(name = "doctor")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Doctor.findAll", query = "SELECT d FROM Doctor d"),
    @NamedQuery(name = "Doctor.findById", query = "SELECT d FROM Doctor d WHERE d.id = :id"),
    @NamedQuery(name = "Doctor.findByNama", query = "SELECT d FROM Doctor d WHERE d.nama = :nama"),
    @NamedQuery(name = "Doctor.findBySalary", query = "SELECT d FROM Doctor d WHERE d.salary = :salary")})
public class Doctor implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 5)
    @Column(name = "id")
    private String id;
    @Size(max = 20)
    @Column(name = "nama")
    private String nama;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Column(name = "salary")
    private Float salary;
    
    /*@OneToMany
    Patient patient;*/

    public Doctor() {
    }

    public Doctor(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNama() {
        return nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public Float getSalary() {
        return salary;
    }

    public void setSalary(Float salary) {
        this.salary = salary;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Doctor)) {
            return false;
        }
        Doctor other = (Doctor) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entity.Doctor[ id=" + id + " ]";
    }
    
}

RumahSakit/src/java/entity/Patient.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Berry
 */
@Entity
@Table(name = "patient")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Patient.findAll", query = "SELECT p FROM Patient p"),
    @NamedQuery(name = "Patient.findById", query = "SELECT p FROM Patient p WHERE p.id = :id"),
    @NamedQuery(name = "Patient.findByNama", query = "SELECT p FROM Patient p WHERE p.nama = :nama"),
    @NamedQuery(name = "Patient.findByAlamat", query = "SELECT p FROM Patient p WHERE p.alamat = :alamat")})
public class Patient implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 5)
    @Column(name = "id")
    private String id;
    @Size(max = 20)
    @Column(name = "nama")
    private String nama;
    @Size(max = 50)
    @Column(name = "alamat")
    private String alamat;

    public Patient() {
    }

    public Patient(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNama() {
        return nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getAlamat() {
        return alamat;
    }

    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Patient)) {
            return false;
        }
        Patient other = (Patient) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entity.Patient[ id=" + id + " ]";
    }
    
}

RumahSakit/src/java/controller/DoctorController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import entity.Doctor;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import javax.ejb.EJB;
import service.DoctorFacade;
import java.util.List;

/**
 *
 * @author Berry
 */
@Named(value = "doctorController")
@SessionScoped
public class DoctorController implements Serializable {

    /**
     * Creates a new instance of DoctorController
     */
    @EJB
    private DoctorFacade df;
    
    private Doctor dr;
    
    public DoctorController() {
        
    }       
    
    public List<Doctor> getAllDoctor() {
        return df.findAll();
    }
    
    public Doctor getDoctor() {
        return dr;
    }
    
    public String prepareCreate() {
        dr = new Doctor();
        return "/AddDoctor";
    }
    
    public String createDoctor() {        
        df.create(dr);      
        return "/index";
    }
    
    
            
}

RumahSakit/src/java/controller/PatientController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import entity.Patient;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import javax.ejb.EJB;
import service.PatientFacade;
import java.util.List;

/**
 *
 * @author Berry
 */
@Named(value = "patientController")
@SessionScoped
public class PatientController implements Serializable {

    /**
     * Creates a new instance of PatientController
     */
    @EJB
    PatientFacade pf;
    Patient pt;
    
    public PatientController() {
    }
    
    public List<Patient> getAllPatient() {
        return pf.findAll();
    }
}

RumahSakit/web/AddDoctor.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Add Doctor</title>
    </h:head>
    <h:body>
        <h:form>
            <!--<p:panelGrid>-->
                <p:outputLabel value="ID Doctor : "/>
                <p:inputText id="iddoc" required="true" value="#{doctorController.doctor.id}"/>
                <p:message for="iddoc" display="text"/>
                
                <p:outputLabel value="Nama : "/>
                <p:inputText id="nmDoc" required="true" value="#{doctorController.doctor.nama}"/>
                <p:message for="nmDoc" display="text"/>
                
                <p:outputLabel value="Salary : "/>
                <p:inputText id="slr" required="true" value="#{doctorController.doctor.salary}"/>
                <p:message for="slr" display="text"/>
            <!--</p:panelGrid>-->
            
            <h:commandButton value="Add" action="#{doctorController.createDoctor()}"/>
        </h:form>
    </h:body>
</html>

RumahSakit/web/AddPatient.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Add Patient</title>
    </h:head>
    <h:body>
        <h:form>
            <p:panelGrid>
                <p:outputLabel for="idPatient" value="ID Patient : "/>
                <p:inputText id="idpat" required="true"/>
                <p:message for="idpat" display="text"/>
                
                <p:outputLabel for="namaPatient" value="Nama : "/>
                <p:inputText id="nmPat" required="true"/>
                <p:message for="nmPat" display="text"/>
                
                <p:outputLabel for="alamat" value="Alamat : "/>
                <p:inputText id="alm" required="true"/>
                <p:message for="alm" display="text"/>
            </p:panelGrid>
            
            <p:commandButton id="submitButton" value="Add" actionListener="" update="panel"/>
        </h:form>
    </h:body>
</html>

RumahSakit/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Rumah Sakit</title>
    </h:head>
    <h:body>
        <h:form id="form">
            <p:tabView>
                <p:tab title="Doctor">
                    <p:dataTable var="doctors" value="#{doctorController.allDoctor}">
                        <p:column headerText="ID Doctor">
                            <h:outputText value="#{doctors.id}"/>
                        </p:column>
                        <p:column headerText="Nama">
                            <h:outputText value="#{doctors.nama}"/>
                        </p:column>
                        <p:column headerText="Salary">
                            <h:outputText value="#{doctors.salary}"/>
                        </p:column>
                    </p:dataTable>
                    <p:button outcome="#{doctorController.prepareCreate()}" value="Add" icon="ui-icon-document"></p:button>
                </p:tab>
                <p:tab title="Patient">
                    <p:dataTable var="patients" value="#{patientController.allPatient}">
                        <p:column headerText="ID Patient">
                            <h:outputText value="#{patients.id}"/>
                        </p:column>
                        <p:column headerText="Nama">
                            <h:outputText value="#{patients.nama}"/>
                        </p:column>
                        <p:column headerText="Alamat">
                            <h:outputText value="#{patients.alamat}"/>
                        </p:column>
                    </p:dataTable>
                    <p:button outcome="AddPatient" value="Add" icon="ui-icon-document"></p:button>
                </p:tab>                
                <p:tab title="Check Up"></p:tab>
            </p:tabView>
        </h:form>
    </h:body>
</html>